# The difference between vector and matrix
## vector
1 dimension
## matrix
more than 1 dimension

# Homework 2 : Julia_1101 Yu_Hao Tseng

## Create a simple one-dimensional array (vector)

In [2]:
a = [1,2,3,4,5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [3]:
b = [1;2;3;4;5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [4]:
a = [1 2 3 4 5] # test

1×5 Matrix{Int64}:
 1  2  3  4  5

## Create a simple one-dimensional array(Something special in Julia)

In [5]:
a1 = [1,2,3.0,4,5]

5-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0
 5.0

In [6]:
s = ["this","is","an","array","of","strings"]

6-element Vector{String}:
 "this"
 "is"
 "an"
 "array"
 "of"
 "strings"

## Create a simple one-dimensional array(Something special in Julia)

In [7]:
mix = [1,"2",3.0,sin,pi] # Mixed array

5-element Vector{Any}:
 1
  "2"
 3.0
  sin (generic function with 13 methods)
 π = 3.1415926535897...

In [8]:
trigfuns = [sin,cos,tan] # Function array

3-element Vector{Function}:
 sin (generic function with 13 methods)
 cos (generic function with 13 methods)
 tan (generic function with 12 methods)


## Create a zero array with known dimension (1D)

In [9]:
array1 = zeros(5) # 5 rows, 1 column

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [10]:
array2 = zeros(5,1) # 5 rows, 1 column

5×1 Matrix{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [11]:
array3 = zeros(1,5)  # 1 rows, 5 column

1×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0

In [12]:
array1 + array2

5×1 Matrix{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [13]:
# array1 + array3
# DimensionMismatch("dimensions must match: a has dims (Base.OneTo(1), Base.OneTo(5)), b has dims (Base.OneTo(5),), mismatch at 1")

## Create a 2D array with known values (Matrix)

In [14]:
array1_2D = zeros(3,5) # 3 rows and 5 columns

3×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [15]:
array2_2D = zeros(5,3) # 5 rows and 3 columns

5×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [16]:
# array1_2D+array2_2D
# DimensionMismatch("dimensions must match: a has dims (Base.OneTo(3), Base.OneTo(5)), b has dims (Base.OneTo(5), Base.OneTo(3)), mismatch at 1")

In [17]:
matrix = [1 2 3;4 5 6] # same as MATLAB

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

## Creating arrays using range objects(comparing to MATLAB)

In [18]:
a = [0:2:20] ## MATLAB style

1-element Vector{StepRange{Int64, Int64}}:
 0:2:20

In [19]:
b = Array(0:2:20) ## Julia style 

11-element Vector{Int64}:
  0
  2
  4
  6
  8
 10
 12
 14
 16
 18
 20

In [20]:
# a+b
# dimensions must match

In [21]:
size(a)

(1,)

In [22]:
size(b)

(11,)

In [23]:
# c = linspace(1,10,5) ## MATLAB style

In [24]:
# d = Array(linspace(1,10,5))

## Changing array types (float <--> integer)

In [25]:
a = 1

1

In [26]:
Float64(a)

1.0

In [27]:
matrix = [1 2 3;4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [28]:
b = Array{Float64}(matrix)

2×3 Matrix{Float64}:
 1.0  2.0  3.0
 4.0  5.0  6.0

In [29]:
c = Array{Int64}(b)

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

## Changing array types (number <--> string)

In [30]:
d = string.(c) # Take note about the dot (dealing the elements individually)

2×3 Matrix{String}:
 "1"  "2"  "3"
 "4"  "5"  "6"

In [31]:
typeof(d) # Check the type

Matrix{String} (alias for Array{String, 2})

In [32]:
size(d) # Check the size

(2, 3)

In [33]:
dd = string(c) # Try an error

"[1 2 3; 4 5 6]"

In [34]:
e = parse.(Float64, d)

2×3 Matrix{Float64}:
 1.0  2.0  3.0
 4.0  5.0  6.0

In [35]:
f = parse.(Int64, d)

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

## Some basic calculations of array(the dot problem) 
When we need the dot?    
-  .*    乘    
- ./      除      
- .^     次方  
- string.(數字array)    數字轉文字  
- float.(文字array)     文字轉數字(浮點數)  
- parse.(Float64,文字array)   文字轉數字(浮點數)  
- parse.(Int64,文字array)   文字轉數字(整數)  


# Exercise 1

## (1) Build three arrays (integer type for A and B, and string type for C) in below:


In [36]:
A = [1 3 1;1 0 1]
B = [2 0 5;7 5 4]
C = ["20071006";"20071010"]

2-element Vector{String}:
 "20071006"
 "20071010"

## (2) Calculate A+B, A-B, A*B and A/B for each element. (hint: remember to dot for some cases)

In [37]:
AB1 = A.+B
AB2 = A.-B
AB3 = A.*B
AB4 = A./B


2×3 Matrix{Float64}:
 0.5       Inf   0.2
 0.142857   0.0  0.25

## (3) Change A to a float array.

In [38]:
A = Array{Float64}(A)

2×3 Matrix{Float64}:
 1.0  3.0  1.0
 1.0  0.0  1.0

## (4) Change all numbers in A to strings.

In [39]:
# A = Array{String}(A)
A = string.(A)

2×3 Matrix{String}:
 "1.0"  "3.0"  "1.0"
 "1.0"  "0.0"  "1.0"

## (5) Change C to an integer array.

In [40]:
C = parse.(Int64, C)

2-element Vector{Int64}:
 20071006
 20071010

## Array Indexing(Some differences with MATLAB)

In [41]:
a = Array(10:10:100)

10-element Vector{Int64}:
  10
  20
  30
  40
  50
  60
  70
  80
  90
 100

In [42]:
a[2]

20

## “Array and Index” problems

In [43]:
a[[2,3,6]] # difference from MATLAB a(2,3,6)

3-element Vector{Int64}:
 20
 30
 60

In [44]:
a[[2,6]] = [0,0]
a[[2,6]].=0

2-element view(::Vector{Int64}, [2, 6]) with eltype Int64:
 0
 0

## Array Indexing(use “findall” function to get indices)

In [45]:
a

10-element Vector{Int64}:
  10
   0
  30
  40
  50
   0
  70
  80
  90
 100

In [46]:
I = findall(a.==0)

2-element Vector{Int64}:
 2
 6

In [47]:
a[I].=99

2-element view(::Vector{Int64}, [2, 6]) with eltype Int64:
 99
 99

## Array Indexing (2D, numbers of rows and columns)

In [48]:
A = [10 20 25;30 40 45]

2×3 Matrix{Int64}:
 10  20  25
 30  40  45

In [49]:
A[1,2]

20

In [50]:
A[2,3]

45

In [51]:
# A[0,1]

In [52]:
# A[1,4]

## Array Indexing (2D, “indices” to “numbers of rows and columns”)

In [53]:
A[1]

10

In [54]:
A[2]

30

In [55]:
A[:,1]

2-element Vector{Int64}:
 10
 30

In [56]:
A[:,3]

2-element Vector{Int64}:
 25
 45

In [57]:
A[2,:]

3-element Vector{Int64}:
 30
 40
 45

## Array Indexing(use “find” function to get indices, for 2D arrays)

In [58]:
a2 = [1 2 3;4 5 6;7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [59]:
I2 = findall(a2.<5)

4-element Vector{CartesianIndex{2}}:
 CartesianIndex(1, 1)
 CartesianIndex(2, 1)
 CartesianIndex(1, 2)
 CartesianIndex(1, 3)

In [60]:
a2[I2].= 0

4-element view(::Matrix{Int64}, CartesianIndex{2}[CartesianIndex(1, 1), CartesianIndex(2, 1), CartesianIndex(1, 2), CartesianIndex(1, 3)]) with eltype Int64:
 0
 0
 0
 0

In [61]:
a2

3×3 Matrix{Int64}:
 0  0  0
 0  5  6
 7  8  9

# Excercise 2 

In [62]:
A = [1 4 3;4 5 4;7 4 9]

3×3 Matrix{Int64}:
 1  4  3
 4  5  4
 7  4  9

In [63]:
I3 = findall(A.==4)

4-element Vector{CartesianIndex{2}}:
 CartesianIndex(2, 1)
 CartesianIndex(1, 2)
 CartesianIndex(3, 2)
 CartesianIndex(2, 3)

In [64]:
A[I3].=0
print(A)

[1 0 3; 0 5 0; 7 0 9]

In [65]:
A = [1 2 3;4 5 6;7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [66]:
I4 = findall(A.!=[1,5,9])

6-element Vector{CartesianIndex{2}}:
 CartesianIndex(2, 1)
 CartesianIndex(3, 1)
 CartesianIndex(1, 2)
 CartesianIndex(3, 2)
 CartesianIndex(1, 3)
 CartesianIndex(2, 3)

In [67]:
A[I4].=0
A

3×3 Matrix{Int64}:
 1  0  0
 0  5  0
 0  0  9

## Concatenation

In [68]:
A = [12]

1-element Vector{Int64}:
 12

In [69]:
A = [A;5]

2-element Vector{Int64}:
 12
  5

In [70]:
A = [1;A]

3-element Vector{Int64}:
  1
 12
  5

In [71]:
cat(A,A; dims = 2) ## for v1.0

3×2 Matrix{Int64}:
  1   1
 12  12
  5   5

In [72]:
A_col = cat(A,A;dims = 2) ## for v1.0

3×2 Matrix{Int64}:
  1   1
 12  12
  5   5

In [73]:
A_row = cat(A,A;dims = 1) ## for v1.0
# 上下合併

6-element Vector{Int64}:
  1
 12
  5
  1
 12
  5

In [74]:
A_row2 = cat(A',A';dims = 1) ## for v1.0
# 左右合併

2×3 Matrix{Int64}:
 1  12  5
 1  12  5

# Homework 02 (2021/10/21)

## 2. Calculate "a = 1+2+3+4+5+...+50"

In [75]:
all = Array(1:1:50)
# 51*25
a = sum(all)

1275

## 3. Given b, find te mean of the 2nd row and the sum of the 3rd column.

In [76]:
b = [1 2 30;4 50 6;70 8 9]

3×3 Matrix{Int64}:
  1   2  30
  4  50   6
 70   8   9

In [77]:
using Statistics

In [78]:
# mean_row2 = sum(b[2,:])/length(b[2,:])
mean_row2 = mean(b[2,:])

20.0

In [79]:
# mean_col3 = sum(b[:,3])/length(b[:,3])
mean_col3 = sum(b[:,3])

45

## 4. Create a function to find the value of speed with any given u and v velocities.  
### $speed = \sqrt{u^2+v^2}$


In [80]:
function sqrt_function(u,v)
    return sqrt(u^2+v^2)
end

sqrt_function (generic function with 1 method)

In [81]:
speed = sqrt_function(9,12)

15.0